#!/bin/bash
# Production Testing Script for Security Fixes
# Tests all security features in production

echo "🧪 CYKEL Security Testing Suite"
echo "================================"
echo ""

PROJECT_ID="cykel-32383"

echo "Test 1: Firestore Rules Deployed ✅"
echo "-----------------------------------"
firebase firestore:rules:get --project $PROJECT_ID | head -20
echo "✓ Rules file should show 683 lines with security fixes"
echo ""

echo "Test 2: Cloud Functions Deployed"
echo "-----------------------------------"
echo "Expected functions:"
echo "  - scheduledCleanupOldMessages"
echo "  - scheduledSecurityMonitoring"
echo "  - scheduledCleanupRateLimits"
echo "  - adminCleanupMessages"
echo "  - adminGetSecurityAlerts"
echo "  - adminGetUserRateLimit"
echo "  - adminClearUserRateLimit"
echo ""
firebase functions:list --project $PROJECT_ID | grep -E "(scheduled|admin)"
echo ""

echo "Test 3: Check Data Migrations"
echo "-----------------------------------"
echo "Open Firebase Console and verify:"
echo "  → Firestore > familyAccounts > Check for 'memberIds' field"
echo "  → Firestore > events > Check for 'participantIds' field"
echo ""
echo "Console: https://console.firebase.google.com/project/$PROJECT_ID/firestore/data"
echo ""

echo "Test 4: App Check Configuration"
echo "-----------------------------------"
echo "Open App Check console:"
echo "https://console.firebase.google.com/project/$PROJECT_ID/appcheck"
echo ""
echo "Verify:"
echo "  ✓ iOS app registered (if applicable)"
echo "  ✓ Android app registered"
echo "  ✓ Green checkmarks on all apps"
echo ""

echo "Test 5: Monitor for Permission Errors"
echo "-----------------------------------"
echo "Watch logs for 'PERMISSION_DENIED' errors:"
firebase functions:log --project $PROJECT_ID --limit 50 | grep -i "permission"
echo ""
echo "If you see permission errors, check:"
echo "  1. User is actually in family memberIds array"
echo "  2. User is actually in event participantIds array"
echo "  3. App Check token is valid"
echo ""

echo "Test 6: Security Monitoring Active"
echo "-----------------------------------"
echo "Check if security monitoring is running:"
echo "Next run should be within 5 minutes (runs every 5 min)"
echo ""
echo "Check Firestore console:"
echo "  → securityAlerts collection should be created"
echo "  → rateLimits collection should be created"
echo ""

echo ""
echo "🎯 Manual Testing in App:"
echo "========================="
echo ""
echo "Family Location Test:"
echo "  1. User A creates family account"
echo "  2. User A can view own location ✓"
echo "  3. User B joins family"
echo "  4. User B can now view User A location ✓"
echo "  5. User C (not in family) tries to view User A location"
echo "  6. User C gets permission denied ✓"
echo ""
echo "Event Chat Test:"
echo "  1. User A creates event"
echo "  2. User A can post/read chat messages ✓"
echo "  3. User B (not joined) tries to view chat"
echo "  4. User B cannot see messages ✓"
echo "  5. User B joins event"
echo "  6. User B can now see and post messages ✓"
echo ""
echo "Rate Limiting Test:"
echo "  1. Try creating 11 marketplace listings quickly"
echo "  2. 11th listing should be rate limited"
echo "  3. Check Firestore > rateLimits collection"
echo ""

echo "✅ Testing Complete!"
echo "Monitor results for 24-48 hours to ensure no issues"
